# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: master # see https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "go.sia.tech*"
        dependency-type: "all"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
