name: Lint & Test
on:
  pull_request:
  push:
    branches:
      - master

env:
  CGO_ENABLED: 1

jobs:
  test:
    uses: SiaFoundation/workflows/.github/workflows/go-test.yml@b42741de5798fcb1881143d714a923501ec4ff89 # master
