name: Lint & Test
on:
  pull_request:
  push:
    branches:
      - master

env:
  CGO_ENABLED: 1

jobs:
  test:
    uses: SiaFoundation/workflows/.github/workflows/go-test.yml@2dc0b0ff59df8c1a5345719e34e62a398f7a165c # master
