name: Main
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ ubuntu-latest , macos-latest, windows-latest ]
        go-version: [ '1.20', '1.21' ]
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false # required on Windows
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        uses: ./.github/actions/test
      - name: Build
        env:
          CGO_ENABLED: 1
        run: go build -o bin/ ./cmd/hostd
