name: Publish V2

# Controls when the action will run.
on:
  # Triggers the workflow when its-happening branch is pushed
  push:
    branches:
      - its-happening

jobs:
  publish:
    uses: SiaFoundation/workflows/.github/workflows/go-publish@master
    secrets: inherit
    with:
      build-args: -trimpath -a -ldflags '-s -w -linkmode external -extldflags "-static"'
      cgo-enabled: 1
      project: hostd
